# Generated by Django 2.0.10 on 2019-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
